FROM node:22-alpine AS dependencies

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --omit=dev


FROM node:22-alpine AS runtime

ENV NODE_ENV=production

WORKDIR /app

RUN addgroup -S appgroup \
    && adduser -S appuser -G appgroup

COPY --from=dependencies \
  /app/node_modules \
  ./node_modules

COPY package.json ./
COPY src ./src

RUN chown -R appuser:appgroup /app

USER appuser

CMD ["npm", "start"]